### ISSUE TITLE
If you try to open a project, the engine will stop.

### ISSUE THREAD

**Issue by YongHyun-Yi** [hiulit/Godot-3-2D-CRT-Shader#4]
After applying the shader, you did not open the project file for a few days.
If you open the project file after a long time, the engine freezes.

**Comment by hiulit** [comment]
Hi, sorry for the late reply.

I don't think the shader would freeze the engine, but could you give more info?

Is this still happening to you?

**Comment by hiulit** [comment]
Please, reopen or create a new issue if this is still happening to you, with more information about your specific error.
